// SPDX-License-Identifier: Apache-2.0

export type LangId = 'description' | 'behavior'

// AST types are generated by ts-rs from Rust structs — single source of truth.
import type {
  OntologyRef,
  AgentDecl,
  AnnotatedRef,
  PropertyType,
  PropertyDecl,
  TypeDefinition,
  DescriptionFile,
  BehaviorFile,
  StateDef,
  TriggerDecl,
  Statement,
} from '@dot-agent/parser-dsl'
export type {
  OntologyRef,
  AgentDecl,
  AnnotatedRef,
  PropertyType,
  PropertyDecl,
  TypeDefinition,
  DescriptionFile,
  BehaviorFile,
  StateDef,
  TriggerDecl,
  Statement,
}

// ── Shared toolchain types ────────────────────────────────────────────────────

/** Structured diagnostic from the Rust WASM parser. */
export interface ParseDiagnostic {
  severity: 'error' | 'warning' | 'info' | 'hint'
  code: string
  message: string
  hint?: string
  /** [line, col] 1-based, absent when position is unavailable (e.g. serde errors). */
  start?: [number, number]
  end?: [number, number]
}

export interface LintMessage {
  file: string
  line: number
  col: number
  severity: 'error' | 'warning' | 'info' | 'hint'
  code: string
  message: string
  hint?: string
}

export interface IdParts {
  namespace: string
  name: string
  version?: string
  digest?: string
}

export interface Capability {
  id: string
  description: string
}

export interface Integrity {
  sha256: string
  types?: string
  files?: string
}

export interface AboutMe {
  dslVersion: string
  id: string
  name: string
  description: string
  version: string
  domain: string
  license: string
  persona?: string
  purpose: string
  compiler: string
  commit?: string
  capabilities: Capability[]
  requires: AnnotatedRef[]
  integrity: Integrity
}

export interface AgentFiles {
  description: string
  behavior: string
  persona?: string
  guides: Array<{ path: string; content: string }>
  knowledge: Array<{ path: string; content: string }>
  behaviors: Array<{ path: string; content: string }>
}

export interface AgentBundle {
  id: string
  aboutme: AboutMe
  files: AgentFiles
}

export interface PackOptions {
  dir?: string
  out?: string
  commit?: string
  version?: string
  description?: string
}

export interface PackResult {
  path: string
  id: string
  warnings: LintMessage[]
}

export interface BuildAboutmeOptions {
  id: string
  name: string
  description: string
  version: string
  domain: string
  license?: string
  persona?: string
  purpose?: string
  compiler: string
  commit?: string
  capabilities?: Capability[]
  requires?: AnnotatedRef[]
  integrity: Integrity
}
