import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const compilerRoot = path.resolve(__dirname, '..')
const monorepoRoot = path.resolve(compilerRoot, '../..')

const dslVersion = fs.readFileSync(path.join(monorepoRoot, 'dsl/VERSION'), 'utf8').trim()
const compilerVersion = JSON.parse(
  fs.readFileSync(path.join(compilerRoot, 'package.json'), 'utf8')
).version

const outPath = path.join(compilerRoot, 'src/generated-version.ts')
const contents = `// Generated by scripts/embed-version.mjs from dsl/VERSION and package.json — do not edit by hand.
export const DSL_VERSION = '${dslVersion}'
export const COMPILER_VERSION = '${compilerVersion}'
`

fs.writeFileSync(outPath, contents)
console.log(`generated ${outPath} (DSL_VERSION=${dslVersion}, COMPILER_VERSION=${compilerVersion})`)
