const envStubs = new Proxy({}, { get: () => () => {} })
let _initialized = false

// `typeof window !== 'undefined'` is not a reliable browser/Node split: Web
// Workers have `fetch` but no `window` (only `self`/`globalThis`), so that
// check sends workers down the Node-only `readFile` branch, which fails once
// bundlers strip/stub `node:fs/promises` for browser targets. Detect Node
// explicitly instead so every non-Node environment (main thread or worker)
// takes the `fetch` path.
export function isNodeRuntime(): boolean {
  return typeof process !== 'undefined' && process.versions?.node != null
}

export async function init(): Promise<void> {
  if (_initialized) return
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const bgModule: any = await import('../../pkg/dot_agent_parser_dsl_bg.js')
  const wasmUrl = new URL('../pkg/dot_agent_parser_dsl_bg.wasm', import.meta.url)
  let wasmBuffer: ArrayBuffer | Uint8Array
  if (isNodeRuntime()) {
    // The `node:` scheme must stay invisible to browser bundlers: webpack throws
    // UnhandledSchemeError and rolldown/tsdown preserves the literal (this is how
    // the 0.10.2 tsup→tsdown migration broke Murici's webpack build). Building the
    // specifier at runtime degrades this to a runtime-only dynamic import — guarded
    // by isNodeRuntime(), so browsers never execute it. `Array.join` is used
    // because rolldown does not constant-fold it back to the static literal.
    const fsSpecifier = ['node:', 'fs/promises'].join('')
    const { readFile } = await import(/* webpackIgnore: true */ fsSpecifier)
    wasmBuffer = await readFile(wasmUrl)
  } else {
    wasmBuffer = await fetch(wasmUrl).then(r => r.arrayBuffer())
  }
  const result = await WebAssembly.instantiate(wasmBuffer as BufferSource, {
    './dot_agent_parser_dsl_bg.js': { ...bgModule },
    env: envStubs,
  }) as WebAssembly.WebAssemblyInstantiatedSource
  bgModule.__wbg_set_wasm(result.instance.exports)
  _initialized = true
}

export {
  parse_behavior,
  parse_description,
  get_graph,
  get_states,
  get_intents_for_state,
} from '../../pkg/dot_agent_parser_dsl.js'

// AST types generated by ts-rs — re-exported as package public API
export type { AgentDecl } from '../../bindings/AgentDecl'
export type { AnnotatedRef } from '../../bindings/AnnotatedRef'
export type { AssignOp } from '../../bindings/AssignOp'
export type { BehaviorFile } from '../../bindings/BehaviorFile'
export type { CompareOp } from '../../bindings/CompareOp'
export type { Condition } from '../../bindings/Condition'
export type { DescriptionFile } from '../../bindings/DescriptionFile'
export type { Expr } from '../../bindings/Expr'
export type { IntentBody } from '../../bindings/IntentBody'
export type { LogicalOp } from '../../bindings/LogicalOp'
export type { MediaKind } from '../../bindings/MediaKind'
export type { MemoryDomain } from '../../bindings/MemoryDomain'
export type { MemoryPath } from '../../bindings/MemoryPath'
export type { OntologyRef } from '../../bindings/OntologyRef'
export type { PropertyDecl } from '../../bindings/PropertyDecl'
export type { PropertyType } from '../../bindings/PropertyType'
export type { RunKind } from '../../bindings/RunKind'
export type { RunModifier } from '../../bindings/RunModifier'
export type { RunStmt } from '../../bindings/RunStmt'
export type { StateDef } from '../../bindings/StateDef'
export type { Statement } from '../../bindings/Statement'
export type { TriggerDecl } from '../../bindings/TriggerDecl'
export type { TypeDefinition } from '../../bindings/TypeDefinition'
export type { Value } from '../../bindings/Value'
