#!/usr/bin/env bash
# Pre-commit hook script — ensures every staged source file has a license
# header before the commit is recorded. Generated by /vibe-ops:license-setup;
# generalized from a scheme first built for a fork-with-dual-attribution case
# — edit the glob below if this repo's source files use other extensions.
#
# Header format: SPDX identifier only, no per-file copyright line. Per ASF's
# own current practice (apache.org/legal/src-headers.html), a copyright line
# on every file is not recommended — it goes stale the moment someone else
# touches the file. Copyright is tracked collectively in NOTICE + AUTHORS.
#
# The script re-stages files it modifies so the header lands in the same commit.
set -euo pipefail

SOURCE_GLOBS=("*.ts" "*.tsx" "*.js" "*.jsx" "*.mjs" "*.cjs" "*.rs")
LICENSE_HEADER='// SPDX-License-Identifier: Apache-2.0'
# Deliberately stricter than the vibe-ops template, which also accepts a bare
# Copyright line to grandfather legacy blocks. Nothing here needs that after the
# SPDX migration, and accepting it would let through exactly what this repo now
# forbids: a personal name in a file header. Attribution is collective (AUTHORS).
HEADER_MARKER='SPDX-License-Identifier'

# Paths that are never stamped. Every entry MUST carry the reason it is here:
# an exclusion with no reason reads as dead config and gets deleted by a later
# reader, silently re-enabling the stamping it was added to prevent.
is_excluded() {
  case "$1" in
    tools/wasi-stub/*)          return 0 ;;  # third-party (Arnaud Golfouse, typst-community/wasm-minimal-protocol) — stamping it would misattribute copyright
    */generated-*|generated-*)  return 0 ;;  # written by a generator; a hand-added header is discarded on the next run
    *) return 1 ;;
  esac
}


# --check mode (used by CI): verify every tracked source file carries a
# license header (either the new SPDX form or an old grandfathered block).
# Read-only — never modifies files; exits 1 if any lack one. Independent of
# the local hook so `--no-verify` / a missing hook can't merge unlicensed code.
if [[ "${1:-}" == "--check" ]]; then
  missing=0
  while IFS= read -r f; do
    [[ -z "$f" || ! -f "$f" ]] && continue
    is_excluded "$f" && continue
    if ! head -10 "$f" | grep -qE "$HEADER_MARKER"; then
      echo "  [license:MISSING] $f"
      missing=$((missing + 1))
    fi
  done <<< "$(git ls-files -- "${SOURCE_GLOBS[@]}")"
  if [[ $missing -gt 0 ]]; then
    echo "ERROR: $missing file(s) missing a license header. Commit locally (the"
    echo "pre-commit hook injects it) or add the header manually."
    exit 1
  fi
  echo "License header check passed."
  exit 0
fi

STAGED=$(git diff --cached --name-only --diff-filter=ACMR -- "${SOURCE_GLOBS[@]}" 2>/dev/null || true)

if [[ -z "$STAGED" ]]; then
  exit 0
fi

injected=0

while IFS= read -r f; do
  [[ -z "$f" || ! -f "$f" ]] && continue
  is_excluded "$f" && continue

  # Already headered → nothing to do
  if head -5 "$f" | grep -q "SPDX-License-Identifier"; then
    continue
  fi

  # Defaults for the plain (non-fork) case; the fork-only block below
  # overrides these when an old dual-license header needs classifying.
  old_header_end=""
  header="$LICENSE_HEADER"
  kind="plain"


  tmpfile="$(mktemp)"
  printf '%s\n\n' "$header" > "$tmpfile"

  if [[ -n "$old_header_end" ]]; then
    body_start=$((old_header_end + 1))
    # also swallow one blank line right after the old block, if present
    if [[ -z "$(sed -n "${body_start}p" "$f")" ]]; then
      body_start=$((body_start + 1))
    fi
    sed -n "${body_start},\$p" "$f" >> "$tmpfile"
    action="migrated"
  else
    cat "$f" >> "$tmpfile"
    action="injected"
  fi

  mv "$tmpfile" "$f"
  git add "$f"

  echo "  [license:$kind:$action] $f"
  injected=$((injected + 1))
done <<< "$STAGED"

if [[ $injected -gt 0 ]]; then
  echo "License headers processed for $injected file(s)."
fi
